export const GROUPS_REQUEST = "GROUPS_REQUEST";
export const GROUPS_SUCCESS = "GROUPS_SUCCESS";
export const GROUPS_FAIL = "GROUPS_FAIL";

export const ADD_GROUP_REQUEST = "ADD_GROUP_REQUEST";
export const ADD_GROUP_SUCCESS = "ADD_GROUP_SUCCESS";
export const ADD_GROUP_FAIL = "ADD_GROUP_FAIL";

export const RENAME_GROUP_REQUEST = "RENAME_GROUP_REQUEST";
export const RENAME_GROUP_SUCCESS = "RENAME_GROUP_SUCCESS";
export const RENAME_GROUP_FAIL = "RENAME_GROUP_FAIL";
