export const LISTS_REQUEST = "LISTS_REQUEST";
export const LISTS_SUCCESS = "LISTS_SUCCESS";
export const LISTS_FAIL = "LISTS_FAIL";

export const ADD_LIST_REQUEST = "ADD_LIST_REQUEST";
export const ADD_LIST_SUCCESS = "ADD_LIST_SUCCESS";
export const ADD_LIST_FAIL = "ADD_LIST_FAIL";

export const RENAME_LIST_REQUEST = "RENAME_LIST_REQUEST";
export const RENAME_LIST_SUCCESS = "RENAME_LIST_SUCCESS";
export const RENAME_LIST_FAIL = "RENAME_LIST_FAIL";
