export const LIST_OPTIONS_MODAL_OPEN = "LIST_OPTIONS_MODAL_OPEN";
export const LIST_OPTIONS_MODAL_CLOSE = "LIST_OPTIONS_MODAL_CLOSE";

export const SORT_MODAL_OPEN = "SORT_MODAL_OPEN";
export const SORT_MODAL_CLOSE = "SORT_MODAL_CLOSE";

export const DUE_DATE_MODAL_OPEN = "DUE_DATE_MODAL_OPEN";
export const DUE_DATE_MODAL_CLOSE = "DUE_DATE_MODAL_CLOSE";

export const PICK_DATE_MODAL_OPEN = "PICK_DATE_MODAL_OPEN";
export const PICK_DATE_MODAL_CLOSE = "PICK_DATE_MODAL_CLOSE";

export const PICK_DATE_AND_TIME_MODAL_OPEN = "PICK_DATE_AND_TIME_MODAL_OPEN";
export const PICK_DATE_AND_TIME_MODAL_CLOSE = "PICK_DATE_AND_TIME_MODAL_CLOSE";

export const REMINDER_MODAL_OPEN = "REMINDER_MODAL_OPEN";
export const REMINDER_MODAL_CLOSE = "REMINDER_MODAL_CLOSE";

export const REPEAT_MODAL_OPEN = "REPEAT_MODAL_OPEN";
export const REPEAT_MODAL_CLOSE = "REPEAT_MODAL_CLOSE";

export const CUSTOM_REPEAT_MODAL_OPEN = "CUSTOM_REPEAT_MODAL_OPEN";
export const CUSTOM_REPEAT_MODAL_CLOSE = "CUSTOM_REPEAT_MODAL_CLOSE";

export const TIME_OPTIONS_MODAL_OPEN = "TIME_OPTIONS_MODAL_OPEN";
export const TIME_OPTIONS_MODAL_CLOSE = "TIME_OPTIONS_MODAL_CLOSE";

export const CALENDAR_MODAL_OPEN = "CALENDAR_MODAL_OPEN";
export const CALENDAR_MODAL_CLOSE = "CALENDAR_MODAL_CLOSE";

export const LIST_ACTIONS_MODAL_OPEN = "LIST_ACTIONS_MODAL_OPEN";
export const LIST_ACTIONS_MODAL_CLOSE = "LIST_ACTIONS_MODAL_CLOSE";

export const GROUP_ACTIONS_MODAL_OPEN = "GROUP_ACTIONS_MODAL_OPEN";
export const GROUP_ACTIONS_MODAL_CLOSE = "GROUP_ACTIONS_MODAL_CLOSE";

export const GROUPS_MODAL_OPEN = "GROUPS_MODAL_OPEN";
export const GROUPS_MODAL_CLOSE = "GROUPS_MODAL_CLOSE";
