export const LIST_OPTIONS_TOOLTIP_OPEN = "LIST_OPTIONS_TOOLTIP_OPEN";
export const LIST_OPTIONS_TOOLTIP_CLOSE = "LIST_OPTIONS_TOOLTIP_CLOSE";

export const SORT_TOOLTIP_OPEN = "SORT_TOOLTIP_OPEN";
export const SORT_TOOLTIP_CLOSE = "SORT_TOOLTIP_CLOSE";

export const DUE_DATE_TOOLTIP_OPEN = "DUE_DATE_TOOLTIP_OPEN";
export const DUE_DATE_TOOLTIP_CLOSE = "DUE_DATE_TOOLTIP_CLOSE";

export const REMINDER_TOOLTIP_OPEN = "REMINDER_TOOLTIP_OPEN";
export const REMINDER_TOOLTIP_CLOSE = "REMINDER_TOOLTIP_CLOSE";

export const REPEAT_TOOLTIP_OPEN = "REPEAT_TOOLTIP_OPEN";
export const REPEAT_TOOLTIP_CLOSE = "REPEAT_TOOLTIP_CLOSE";

export const SUGGESTIONS_TOOLTIP_OPEN = "SUGGESTIONS_TOOLTIP_OPEN";
export const SUGGESTIONS_TOOLTIP_CLOSE = "SUGGESTIONS_TOOLTIP_CLOSE";
